sudo: 'required'
cache:
  directories:
    - $HOME/google-cloud-sdk
env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - SHA=$(git rev-parse HEAD)
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - if [ ! -d $HOME/google-cloud-sdk/bin ]; then
      rm -rf $HOME/google-cloud-sdk;
      curl https://sdk.cloud.google.com | bash > /dev/null;
    fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-273311
  - gcloud config set compute/zone asia-east1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t 683202/react-test -f ./client/Dockerfile.dev ./client
  # Just built the react-project for now as this is the only project with tests.
  # Other projects like nginx, server and worker will be built and pushed to the docker hub right away.
script:
  - docker run -e CI=true 683202/react-test npm run test -- --coverage
  # In the command above, the default command specified in the Dockerfile for the container is
  # overridden by the command `npm run test -- --coverage`
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master